// The revision logic, checked three ways.
//
//   1. EDGE CASES the real library does not happen to contain — two-digit
//      years, an unreadable date, two revisions on the same day. Pure; runs
//      everywhere.
//   2. A COMMITTED SNAPSHOT of the desktop app's own answers, over four real
//      projects with their client details scrubbed out (tests/data/). Runs
//      everywhere. This is the regression check: if the port's ranking drifts,
//      this fails on any machine, in CI, in a fresh clone.
//   3. A LIVE DIFFERENTIAL against pdf_fast_viewer.py itself, over the real
//      library. Only where both are present. This is the one that keeps the
//      snapshot honest: if the DESKTOP's rule changes, (3) fails here and the
//      snapshot gets regenerated — (2) alone would happily freeze a rule that
//      no longer matches the program it is meant to agree with.
//
// (2) is generated by `python tests/revisions-python-truth.py --anonymise ...`
// — see the header of tests/data/README.md.
//
// Run: node tests/revisions-logic.mjs
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  parseRevisionDate, revisionRank, compareRank, normalizeSheetLabel,
  resolveLatestSheets, visibleRevisions, autoMatchPages, sheetVersions,
  newestVersionOf, rowPlan, shiftRevisionIndices,
} from '../js/core/revisions.js';
import { LIBRARY, DESKTOP_SRC, DATA, haveLibrary, haveDesktopSource } from './config.mjs';

const run = promisify(execFile);
let fails = 0;
let checks = 0;

function eq(label, got, want) {
  checks += 1;
  const a = JSON.stringify(got), b = JSON.stringify(want);
  if (a === b) return true;
  fails += 1;
  const show = s => (s && s.length > 400 ? s.slice(0, 400) + ` … (${s.length})` : s);
  console.log(`FAIL ${label}\n  got  ${show(a)}\n  want ${show(b)}`);
  return false;
}
const ok = (label, cond) => eq(label, !!cond, true);

// ═══ 1. edge cases ════════════════════════════════════════════════════════
{
  eq('two-digit year 69 → 2069', parseRevisionDate('1/2/69'), [2069, 1, 2]);
  eq('two-digit year 70 → 1970', parseRevisionDate('1/2/70'), [1970, 1, 2]);
  eq('iso is y-m-d', parseRevisionDate('2026-08-19'), [2026, 8, 19]);
  eq('month 13 is unreadable', parseRevisionDate('13/2/2026'), null);
  eq('day 32 is unreadable', parseRevisionDate('1/32/2026'), null);
  eq('blank is unreadable', parseRevisionDate(''), null);
  eq('words are unreadable', parseRevisionDate('last tuesday'), null);
  eq('the first field is the MONTH unless it is > 31',
    [parseRevisionDate('3-4-2026'), parseRevisionDate('2026-3-4')],
    [[2026, 3, 4], [2026, 3, 4]]);

  // An UNDATED revision still outranks the ORIGINAL. Deliberate: a set that
  // was re-issued is newer than one that was not, whatever the typist left out.
  const undated = { id: 'u', date: '', match: { 0: 0 }, extra: {}, pageCount: 1 };
  eq('undated revision beats the original',
    resolveLatestSheets(['A1'], [], [undated], { order: 'date' }).rows[0].from,
    ['rev', 0, 0]);

  // Same day, two revisions: the later COLUMN wins.
  const a = { id: 'a', date: '07/24/2026', description: 'first', match: { 0: 0 }, extra: {}, pageCount: 1 };
  const b = { id: 'b', date: '07/24/2026', description: 'second', match: { 0: 0 }, extra: {}, pageCount: 1 };
  eq('same day → later column wins',
    resolveLatestSheets(['A1'], [], [a, b], { order: 'date' }).rows[0].from, ['rev', 1, 0]);
  eq('a dated revision beats an undated one whatever the column order',
    resolveLatestSheets(['A1'], [], [a, undated], { order: 'date' }).rows[0].from, ['rev', 0, 0]);

  // A match pointing past the end of the set is not a version.
  const bad = { id: 'x', date: '07/24/2026', match: { 0: 9 }, extra: {}, pageCount: 1 };
  eq('out-of-range match is ignored',
    resolveLatestSheets(['A1'], [], [bad], { order: 'date' }).rows[0].from, ['main', 0]);
  eq('out-of-range match is not a version', sheetVersions(0, [bad]).length, 1);

  // A set with no pages must not occupy a column — the desktop drops it, so
  // leaving it in would shift every column number after it.
  const empty = { id: 'e', date: '01/01/2026', match: { 0: 0 }, extra: {}, pageCount: 0 };
  eq('a revision with no images is not visible', visibleRevisions([empty]).length, 0);

  eq('unfilled slot is not a row',
    resolveLatestSheets(['A1'], [{ id: 'xs-z', after: 0, label: 'Z' }], [a],
      { order: 'date', includeNew: false }).rows.length, 1);

  eq('normalizeSheetLabel folds punctuation and case',
    ['S-2.1', 'S2.1', 's 2 1'].map(normalizeSheetLabel), ['S21', 'S21', 'S21']);
  ok('compareRank orders the three tiers',
    compareRank(revisionRank({ date: '01/01/2026' }, 0), revisionRank({ date: '' }, 9)) > 0);
}

// ── index shifting: the thing that corrupts a file silently ───────────────
{
  const revs = [{ id: 'r1', match: { 0: 0, 2: 1, 5: 2 }, extra: {}, pageCount: 3 }];
  const extra = [{ id: 'xs-a', after: -1 }, { id: 'xs-b', after: 2 }, { id: 'xs-c', after: 5 }];
  const sv = { 2: 'r1', 5: 'r1' };
  shiftRevisionIndices(revs, extra, sv, 2, +1);
  eq('insert at 2 · match', revs[0].match, { 0: 0, 3: 1, 6: 2 });
  eq('insert at 2 · extra after', extra.map(s => s.after), [-1, 3, 6]);
  eq('insert at 2 · sheet_version', sv, { 3: 'r1', 6: 'r1' });

  const revs2 = [{ id: 'r1', match: { 0: 0, 2: 1, 5: 2 }, extra: {}, pageCount: 3 }];
  const extra2 = [{ id: 'xs-a', after: -1 }, { id: 'xs-b', after: 2 }, { id: 'xs-c', after: 5 }];
  const sv2 = { 2: 'r1', 5: 'r1' };
  shiftRevisionIndices(revs2, extra2, sv2, 2, -1);
  eq('delete 2 · match drops that sheet', revs2[0].match, { 0: 0, 4: 2 });
  eq('delete 2 · extra after', extra2.map(s => s.after), [-1, 1, 4]);
  eq('delete 2 · sheet_version drops it', sv2, { 4: 'r1' });
}

// ═══ shared: run one truth record through the port ════════════════════════
function checkAgainst(p, label) {
  const revs = p.revisions.map((r, i) => ({ ...r, pageCount: p.blob_counts[i] || 0 }));

  p.revisions.forEach((rev, c) => {
    eq(`${label} · parseRevisionDate(${JSON.stringify(rev.date)})`,
      parseRevisionDate(rev.date), p.ranks[c].parsed);
    eq(`${label} · revisionRank col ${c} (date)`,
      revisionRank(rev, c, 'date'), p.ranks[c].rank_date);
    eq(`${label} · revisionRank col ${c} (column)`,
      revisionRank(rev, c, 'column'), p.ranks[c].rank_col);
  });
  for (const [lbl, want] of Object.entries(p.normalized_labels)) {
    eq(`${label} · normalizeSheetLabel(${JSON.stringify(lbl)})`,
      normalizeSheetLabel(lbl), want);
  }

  for (const order of ['date', 'column']) {
    for (const includeNew of [true, false]) {
      const key = `latest.${order}.${includeNew ? 'new' : 'nonew'}`;
      const want = p[key];
      const got = resolveLatestSheets(p.main_labels, p.extra_sheets, revs,
        { order, includeNew });
      eq(`${label} · ${key} · notes`, got.notes, want.notes);
      eq(`${label} · ${key} · row count`, got.rows.length, want.rows.length);
      const n = Math.min(got.rows.length, want.rows.length);
      const norm = r => ({
        sheet: r.sheet, source: r.source, date: r.date, from: r.from,
        versions: r.versions, kind: r.kind,
        usedCol: r.usedCol === undefined ? r.used_col : r.usedCol,
        cols: Object.fromEntries(Object.entries(r.cols)
          .map(([k, v]) => [String(k), v])
          .sort((x, y) => Number(x[0]) - Number(y[0]))),
      });
      for (let i = 0; i < n; i++) {
        if (!eq(`${label} · ${key} · row ${i}`, norm(got.rows[i]), norm(want.rows[i]))) break;
      }
    }
  }

  // The row plan and the Current Set must agree about which rows exist.
  eq(`${label} · rowPlan length matches the no-orphan row count`,
    rowPlan(p.main_labels, p.extra_sheets, revs).length,
    p['latest.date.nonew'].rows.length);

  // sheetVersions and newestVersionOf must agree with the column the Current
  // Set picked, sheet by sheet.
  for (let i = 0; i < p.main_labels.length; i++) {
    const row = p['latest.date.nonew'].rows.find(
      r => r.kind === 'main' && r.cols['0'] && r.cols['0'][1] === i);
    if (!row) continue;
    eq(`${label} · sheet ${i} version count`,
      sheetVersions(i, revs).length, Object.keys(row.cols).length);
    const wantId = row.used_col === 0 ? '' : String(revs[row.used_col - 1].id);
    eq(`${label} · sheet ${i} newestVersionOf`, newestVersionOf(i, revs, 'date'), wantId);
  }
}

// ═══ 2. the committed snapshot — runs everywhere ══════════════════════════
{
  const file = new URL('revisions-truth.json', DATA);
  let snapshot = null;
  try {
    snapshot = JSON.parse(await readFile(file, 'utf-8'));
  } catch {
    fails += 1;
    console.log('FAIL tests/data/revisions-truth.json is missing — it is committed, '
      + 'so this should not happen. Regenerate it with:\n'
      + '  python tests/revisions-python-truth.py --anonymise <projects…> '
      + '> tests/data/revisions-truth.json');
  }
  if (snapshot) {
    console.log(`-- committed snapshot: ${snapshot.length} projects, `
      + `${snapshot.reduce((n, p) => n + p['latest.date.new'].rows.length, 0)} rows --`);
    for (const p of snapshot) checkAgainst(p, p.file.replace('.takeoff', ''));
  }
}

// ═══ 3. the live differential — only where the data is ════════════════════
const canDiff = (await haveLibrary()) && (await haveDesktopSource());
if (!canDiff) {
  console.log('\n-- live differential SKIPPED '
    + '(needs PTT_LIBRARY and PTT_DESKTOP_SRC) --');
} else {
  console.log('\n-- live differential vs pdf_fast_viewer.py --');
  const here = path.dirname(fileURLToPath(import.meta.url));
  const script = path.join(here, 'revisions-python-truth.py');

  // Pick the projects that actually carry revisions, so the diff is about
  // revisions rather than about how many files the library happens to have.
  const { withRevisions } = await import('./lib-scan.mjs');
  const projects = await withRevisions(4);
  if (!projects.length) {
    console.log('   (no project in PTT_LIBRARY has a revision tail)');
  } else {
    let truth;
    try {
      const { stdout } = await run('python', [script, ...projects],
        { maxBuffer: 1 << 28, windowsHide: true,
          env: { ...process.env, PTT_DESKTOP_SRC: DESKTOP_SRC } });
      truth = JSON.parse(stdout);
    } catch (err) {
      fails += 1;
      console.log('FAIL could not run the python truth script:', err.message);
    }
    if (truth) {
      for (const p of truth) checkAgainst(p, p.file.slice(0, 26));
      console.log(`   (${truth.length} real projects, `
        + `${truth.reduce((n, p) => n + p['latest.date.new'].rows.length, 0)} rows)`);

      // autoMatchPages, over a real stored map. The stored one is
      // hand-corrected, so some difference is expected — none at all would
      // mean the auto-matcher was not being exercised.
      const p0 = truth.find(t => t.revisions.length);
      if (p0) {
        const rev = p0.revisions[0];
        const re = autoMatchPages(p0.main_labels, rev.page_labels);
        let agree = 0;
        for (const [k, v] of Object.entries(re)) {
          if (rev.match[k] !== undefined && rev.match[k] === v) agree += 1;
        }
        ok('autoMatchPages agrees with the stored map somewhere', agree > 0);
      }
    }
  }
}

console.log(fails
  ? `\n${fails} of ${checks} checks FAILED`
  : `\nAll ${checks} checks pass — the port agrees with the desktop app`
    + (canDiff ? ' (snapshot + live differential)' : ' (snapshot; live differential skipped)'));
process.exit(fails ? 1 : 0);
